### ISSUE TITLE
Gitlab output not as expected

### ISSUE THREAD

**Issue by Marvin-Brouwer** [PhilippHeuer/docker-gitlab-powershell#1]
When Running powerShell in my CI Runner I get very strange Offsets by the output.
Also The color is ignored.

Example: 
- https://www.screencast.com/t/a8yMB08jHK
- https://www.screencast.com/t/L1ucVUOBx

**Comment by PhilippHeuer** [comment]
I once created this image because you couldn't overwrite the entrypoint in your gitlab-ci.yml - now you can so you don't have to use this image anymore - just use the official one.

About that issue, is possible that your powershell scripts output colors in the windows format which breaks the linux terminal output? I would try to disable color output if possible.

**Comment by Marvin-Brouwer** [comment]
Thank you very much, I tried this because the windows/powershell image failed.
I probably made a mistake referencing.
I do still have the same issue there tho.
